### ISSUE TITLE
Help Output Formatting in 1.0.25

### ISSUE THREAD

**Issue by jasonmacdee** [Archomeda/AutoSaliens#1]
The help command's output is somewhat unreadable. Screenshot is from Windows 10, AutoSaliens version 1.0.25. I assume this isn't the intended format of the help command. :)

In case it's relevant, the window width is 150, height 30.

![image](https://user-images.githubusercontent.com/7330491/41854502-66677c36-785e-11e8-9026-348ba156ff6c.png)

**Comment by Archomeda** [comment]
Ouch, that definitely isn't supposed to happen. I'll take a look into it.

**Comment by Archomeda** [comment]
When I included colors, I changed some more things in the console. New lines were probably broken because of that, depending what OS you're running it on.

I fixed it, you can find the latest build at the same url: https://ci.appveyor.com/project/Archomeda/AutoSaliens/branch/master/artifacts

Let me know if some other outputs are broken.

**Comment by jasonmacdee** [comment]
Verified fixed in 1.0.37. Excellent! Thank you!
